[general]
live_config_reload = true

[bell]
animation = "EaseOutExpo"
color = "0xffffff"
duration = 0

[colors]
draw_bold_text_with_bright_colors = true

[colors.bright]
black = "0x44475a"
blue = "0xcaa9fa"
cyan = "0x9aedfe"
green = "0x5af78e"
magenta = "0xff92d0"
red = "0xff6e67"
white = "0xe6e6e6"
yellow = "0xf4f99d"

[colors.normal]
black = "0x000000"
blue = "0xcaa9fa"
cyan = "0x8be9fd"
green = "0x50fa7b"
magenta = "0xff79c6"
red = "0xff5555"
white = "0xbfbfbf"
yellow = "0xf1fa8c"

[colors.primary]
background = "0x282a36"
foreground = "0xf8f8f2"

[cursor]
style = "Block"
unfocused_hollow = true

[env]
TERM = "xterm-256color"

[font]
size = 9.0

[font.bold]
family = "MesloLGSDZ Nerd Font Mono"
style = "Regular"

[font.glyph_offset]
x = 0
y = 0

[font.italic]
family = "MesloLGSDZ Nerd Font Mono"
style = "Italic"

[font.normal]
family = "MesloLGSDZ Nerd Font Mono"
style = "Regular"

[font.offset]
x = 0
y = 0

[mouse]
hide_when_typing = true

[scrolling]
history = 10000
multiplier = 3

[selection]
save_to_clipboard = true
semantic_escape_chars = ",â”‚`|:\"' ()[]{}<>"

[window]
decorations = "full"
dynamic_padding = false
dynamic_title = false
opacity = 1

[window.dimensions]
columns = 130
lines = 42

[window.padding]
x = 2
y = 2
